# Generated by Django 5.1.2 on 2024-12-03 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistory',
        ),
    ]
