# Generated by Django 5.1.2 on 2024-12-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
    ]
